FROM golang:alpine

RUN apk update && apk add --no-cache git

WORKDIR /app

ARG APP_PORT
ARG API_KEY
ARG DB_USERNAME
ARG DB_PORT
ARG DB_PASSWORD
ARG DB_DATABASE
ARG DB_HOST
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV APP_PORT=$APP_PORT
ENV API_KEY=$API_KEY
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PORT=$DB_PORT
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DATABASE=$DB_DATABASE
ENV DB_HOST=$DB_HOST

COPY . .

RUN go mod tidy

RUN go build -o ppdb_sekolah

EXPOSE 8000

ENTRYPOINT ["/app/ppdb_sekolah"]
