name: Deploy PPDB to Cloud run

on:
  push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
            project_id: deploy-api-phyton
            service_account_key: ${{secrets.GCLOUD_AUTH}}

      - name: Configure Docker to use gcloud 
        run: |
            gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
       
      - name: Set Environment Variables
        run: |
            echo "APP_PORT=${{ secrets.APP_PORT }}" >> $GITHUB_ENV
            echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
            echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image 
        run: |
            export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
            export IMAGE_NAME=asia-southeast1-docker.pkg.dev/deploy-api-phyton/ppdb/ppdb_sekolah:${IMAGE_TAG}
            docker build --build-arg DB_USERNAME=$DB_USERNAME \
                         --build-arg DB_PASSWORD=$DB_PASSWORD \
                         --build-arg DB_DATABASE=$DB_DATABASE \
                         --build-arg API_KEY=$API_KEY \
                         --build-arg DB_HOST=$DB_HOST \
                         --build-arg DB_PORT=$DB_PORT \
                         --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
                         --build-arg APP_PORT=$APP_PORT \
                         -t ${IMAGE_NAME} .
            docker push ${IMAGE_NAME}
      - name: Deploy to Cloud Run
        run: |
            export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
            export IMAGE_NAME=asia-southeast1-docker.pkg.dev/deploy-api-phyton/ppdb/ppdb_sekolah:${IMAGE_TAG}
            gcloud run deploy ppdb-sekolah --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated
        # env:
        #     CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
